[features]
seeds = false
skip-lint = false
[programs.localnet]
janecek_method = "CMBTneJJ1youyuhCW6rwwxmgy2Cb2vRuSECRjkMFmg9k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/janecek-method-test.ts"
