[features]
seeds = false
skip-lint = false
[programs.localnet]
janecek_method = "fZiPQcexEoTQJxdzwKEaCwMTMtnX1b7PSjPmoBoM3mj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/janecek-method-test.ts"
